config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  get 'home/about' => 'home#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :books, only: [:new, :create, :index, :show, :edit, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :index, :edit, :update]

  resources :relationships, only: [:create, :destroy]

  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true,
                   length: { maximum: 200 }

  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  attachment :profile_image
  # フォロー機能
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    followings.include?(other_user)
  end
  # フォロー機能
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :correct_user, only: [:destroy]

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    book = Book.find(params[:book_id])
    comment = BookComment.find(params[:id])
    comment.destroy
    redirect_to book_path(book)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

  def correct_user
    comment = current_user.book_comments.find_by(id: params[:id])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user, { only: [:edit, :update, :destroy] }
  # (ログインユーザー以外の人が情報を遷移しようとした時に制限をかける)

  def new
    @Book = Book.new
  end

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def create
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have creatad book successfully."
      redirect_to book_path(@book.id)
    # redirect_to "/books/#{@book.id}"

    else
      @books = Book.all
      flash[:notice] = "errors prohibited this obj from being saved:"
      render "index"
     end
  end

  def show
    @user = current_user
    @book = Book.find(params[:id])
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have creatad book successfully."
      redirect_to book_path(@book.id)

    else
      @books = Book.all
      flash[:notice] = ' errors prohibited this obj from being saved:'
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to "/books"
  end

  def ensure_current_user
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to book_path
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

  def user_params
    params.require(:user).permit(:name, :image, :introduction)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @book.favorites.create(user_id: current_user.id)
  end

  def destroy
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end

  private

  def favorite_params
    params.require(:favorite).permit(:user_id, :book_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:relationship][:follow_id])
    following = current_user.follow(@user)
    if following.save
      flash[:success] = 'ユーザーをフォローしました'
      redirect_to @user
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_to user
    end
  end

  def destroy
    @user = User.find(params[:relationship][:follow_id])
    following = current_user.unfollow(@user)
    if following.destroy
      flash[:success] = 'ユーザーのフォローを解除しました'
      redirect_to @user
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_to user
    end
  end

  def followings
    @users = current_user.followings
  end

  def followers
    @users = current_user.followers
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  # (ログインしていない状態で他のページに遷移しようとした場合、ログインページに繊維する)
  before_action :ensure_current_user, { only: [:edit, :update, :destroy] }
  # (ログインユーザー以外の情報を遷移しようとした時に制限をかける)

  def new
    @user = User.new
    @book = Book.new
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
    end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to "/users/#{current_user.id}"
    else
      flash[:notice] = "errors prohibited this obj from being saved:"
      render :edit

    end
   end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def ensure_current_user
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)

    end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="box2">

<h1>Editing Book</h1>
<%= form_for(@book, url: book_path(@book.id)) do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title,class:"col-xs-12" %>
    <h4>Opinion</h4>

    <%= f.text_area :body,class:"col-xs-12" %>

  <nav>
     <%= f.submit 'Update Book',class: "col-xs-12 btn btn-primary" %>
  </nav>
　<% end %>

<%= link_to "Show",book_path(@book.id)%>
<%= link_to "Back",books_path %>

</div>

app/views/books/index.html.erb
<% if @book.errors %>
   <ul>
<% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
       <% end %>
        </ul>
      <% end %>


<div class="container">
  <div class="row">
    <div class= "col-xs-3">
      <h2>User info</h2> 
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "m_e_others_471.jpg" ,format: 'm_e_others_471.jpg' %>

    <table>
    <tbody>
      <tr></tr>
      <tr> 
      <th><h5>name</h5></th>

      <th><%= @user.name %></th>
      </tr>

      
      <tr>
      <th><h5>introduction</h5></th>
      <th></th>
      <th><%= @user.introduction %></th>
      </tr>

    </tbody>
    </table>
     

      <%= link_to"",edit_user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>

       <%= form_for(@book,  url: books_path) do |f| %>

       <h2>New book</h2>
       <h5>title</h5>
        <%= f.text_field :title,class: "col-xs-12" %>

       <h5>opinion</h5>
       <%= f.text_field :body,class: "col-xs-12" %>

       <nev>
         <%= f.submit 'Create Book',class: "col-xs-12 btn btn-primary" %>
       </nev>
      <% end %>
    </div>

    <div class= "col-xs-9">
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>
        <tr>
          <th></th>
          <th>title</th>
          <th>opinion</th>
          <th colspan="3"></th>
        </tr>


         <% @books.each do |book| %>
      	<tr>
      		<td><%= link_to user_path(book.user_id) do %>
      		<%= attachment_image_tag book.user, :profile_image, :fill, 20, 20, fallback: "l_e_others_470.jpg",size:'20x20',format: 'l_e_others_470.jpg' %></td>
      		<% end %>
      		<td><%=link_to book.title, book_path(book.id)%></td>
      		<td><%=link_to book.body %></td>

          <% if book.favorited_by?(current_user) %>
          <td>
            <%= link_to book_favorites_path(book), method: :delete do %>
              <i class="fa fa-heart" aria-hidden="true" style="color: red"></i>
            <%= book.favorites.count %>いいね
            <% end %>
          </td>
          <% else %>
          <td>
              <%= link_to book_favorites_path(book), method: :post do %>
              <i class="fa fa-heart-o" aria-hidden="true"></i>
              <%= book.favorites.count %>いいね
              <% end %>
          </td>
          <% end %>
          <!-- いいね -->

          <td><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></td>
      	</tr>
      <% end %>
      </table>
    </div>


  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class= "col-xs-3">
      <h2>User info</h2> 
      <!-- あとで編集いるかも -->
     <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "m_e_others_471.jpg" ,format: 'm_e_others_471.jpg' %>

      <h5>name</h5>
      <%= @user.name %>

      <h5>introduction</h5>
      <%= @user.introduction %>
     

      <%= link_to"",edit_user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>

       <%= form_for(@book,  url: books_path) do |f| %>

       <h2>New book</h2>
       <h5>title</h5>
        <%= f.text_field :title,class: "col-xs-12" %>

       <h5>opinion</h5>
       <%= f.text_field :body,class: "col-xs-12" %>

       <nev>
         <%= f.submit 'Create Book',class: "col-xs-12 btn btn-primary" %>
       </nev>
      <% end %>
    </div>

    <div class= "col-xs-9">
      <h2>Book detail</h2>
      <table class='table table-hover table-inverse'>
        <tr>
        	<td>
        		 <%= link_to user_path(@book.user_id) do %>
        		 <%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, fallback: "l_e_others_470.jpg",size:'50x50',format: 'l_e_others_470.jpg' %>
        		 <nav>
        		 	<%= @book.user.name %>
        		 </nav>
        		 <% end %>
        	</td>
        	 <td><%= link_to @book.title %></td>
        	 <td><%= @book.body %></td>

          <% if @book.favorited_by?(current_user) %>
          <td>
            <%= link_to book_favorites_path(@book), method: :delete, remote: true do %>
              <i class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></i>
            <%= @book.favorites.count %>いいね
            <% end %>
          </td>
          <% else %>
          <td>
             <%= link_to book_favorites_path(@book), method: :post, remote: true do %>
              <i class="glyphicon glyphicon-heart-empty" aria-hidden="true"></i>
            <%= @book.favorites.count %>いいね
            <% end %>
          </td>
          <% end %>

            <td>
            <i class="fa fa-comment"></i>
            <a href="#comments">コメント数：<%= @book.book_comments.count %></a>
            </td>
            <div class="comment-list bt style-2" id="comment" >

            <td><% if @book.user == current_user %>
              <%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %>
              <% end %>
            </td>
              
            <td><% if @book.user == current_user %>
              <%= link_to "Destroy",book_path(@book.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %>
              <% end %>
            </td>
        </tr>
      </table>

      <table class="comment-list">
        <% @book.book_comments.each do |book_comment| %>
        <tr class="comment">
        <div class="comment-body bb">
          <td>
            <div class="comment-avatar">
              <div class="avatar">
                <%= attachment_image_tag(book_comment.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
              </div>
            </div>

            <div class="comment-author clearfix">
              <a href="#" class="link-author"><%= book_comment.user.name %></a>
            </div>
          </td>

          <td>
            <span class="comment-meta"></span>
            <div class="comment-entry"><%= book_comment.comment %></div>
          </td>

          <td>
            <span>
              <% if book_comment.user == current_user %>
              <%= link_to "Destroy",book_book_comment_path(@book, book_comment), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{book_comment.id}" %>
              <% end %>
            </span>
          </td>
        </div>
        </tr>
        <% end %>
      </table>

      <div class="row">
        <%= form_for [@book, @book_comment] do |f| %>
            
          <%= f.text_area :comment, rows:'5', class: "col-xs-10 comment-form",placeholder: "comment" %>
          <%= f.submit "送信", class: "btn btn-default btn-sm btn-base-1 pull-left" %>
        <% end %>
      </div>


    </div>
  </div>
</div>

app/views/home/about.html.erb
<div class="box">
<title>Bookers2</title>

<h1>Welcome to<span class='glyphicon glyphicon-book'></span><strong>Bookers!</strong></h1>

</div>

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      <h1 align="left">welcome to <i class="glyphicon glyphicon-book"></i>Bookers   !!</h1>
      <p align="left">In<i class="glyphicon glyphicon-book"></i>Bookers,</p>
      <p align="left">you can share and exchange your options,inpressiond,and emotions</p>
      <p align="left">about varioius books!</p>

      <%= link_to "Log in",new_user_session_path ,class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %>

      <%= link_to "Sign Up",new_user_registration_path ,class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %>
    </div>
    <h1 class="jquery">Hello jQuery!</h1>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
-if model.errors.any? 
  .alert
    %ul
      -model.errors.full_messages.each do |message| 
        %li= message

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left" >
        <span class="text-muted" style="font-size: 20px;">Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                  <li class="">
                      <%= link_to user_path(current_user.id) do %>
                          <i class="glyphicon glyphicon-home home"></i>
                          <span>Home</span>
                      <% end %>
                  </li>
                  <li class="">
                      <%= link_to users_path do %>
                          <i class="glyphicon glyphicon-user users"></i>
                          <span>Users</span>
                      <% end %>
                  </li>
                  <li class="">
                      <%=link_to books_path do %>
                          <i class="glyphicon glyphicon-book books"></i>
                          <span>Books</span>
                      <% end %>
                  </li>
                  <li class="">
                      <%= link_to destroy_user_session_path, method: :delete do %>
                          <i class="glyphicon glyphicon-log-out logout"></i>
                          <span>logout</span>
                      <% end %>
                  </li>
                  
              <% else %>
                  <li class="">
                      <%= link_to root_path do %>
                          <i class="glyphicon glyphicon-home home"></i>
                          <span>Home</span>
                      <% end %>
                  </li>
                  <li class="">
                    <!-- あとで編集の必要 -->
                      <%= link_to home_about_path do %>
                          <i class="glyphicon glyphicon-link about"></i>
                          <span>About</span>
                      <% end %>
                  </li>
                  <li class="">
                      <%= link_to new_user_registration_path do %>
                          <i class="glyphicon glyphicon-edit sign_up"></i>
                          <span>sign up</span>
                      <% end %>
                  </li>
                  <li class="">
                      <%= link_to new_user_session_path do %>
                          <i class="glyphicon glyphicon-log-in sign_in"></i>
                          <span>login</span>
                      <% end %>
                  </li>
              <% end %>
          </ul>
        </nav>
      </div>
    </header>

     
    <div class= "body">
      <% if flash[:notice] %>
        <div class="flash">
          <%= flash[:notice] %>
        </div>
      <% end %>
    </div>
    <%= yield %>


    <footer>
      <div class='container'>
        <div class='row'>
          <div class='col-xs-3 col-xs-offset-9'>
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/relationships/_follow_button.html.erb
     <% if current_user != user %>
        <% if current_user.following?(user) %>
        <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
          <%= f.hidden_field :follow_id, value: user.id %>
          <%= f.submit 'フォロー中', class: 'follow-now' %>
        <% end %>
        <% else %>
        <%= form_for(current_user.relationships.build) do |f| %>
          <%= f.hidden_field :follow_id, value: user.id %>
          <%= f.submit 'フォロー', class: 'follows' %>
        <% end %>
        <% end %>
     <% end %>

app/views/relationships/followers.html.erb
<div>
	<h1>followers</h1>
	<table class='table table-hover table-inverse'>
		<tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>


        <% @users.each do |user| %>

        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 20, 20, fallback: "l_e_others_470.jpg",size:'20x20',format: 'l_e_others_470.jpg' %></td>          
          </td>
          <td><%= user.name %><td>

          <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
        </tr>
        <% end %>
	</table>
</div>

app/views/relationships/followings.html.erb
<div>
	<h1>following</h1>
	<table class='table table-hover table-inverse'>
		<tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>


        <% @users.each do |user| %>

        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 20, 20, fallback: "l_e_others_470.jpg",size:'20x20',format: 'l_e_others_470.jpg' %></td>          
          </td>
          <td><%= user.name %><td>

          <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
        </tr>
        <% end %>
	</table>
</div>

app/views/users/edit.html.erb
<% if @user.errors %>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      <% end %>

<div class="box">
<h2>User info</h2>

<%= form_for(@user, url: user_path(current_user.id)) do |f| %>
    <h4>Name</h4>
    <%= f.text_field :name %>
    <h4>Image</h4>
  	 <%= f.attachment_field :profile_image %>
    <h4>introduction</h4>
    <%= f.text_area :introduction %>

    <%= f.submit 'Update User' %>

<% end %>

</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class= "col-xs-3">
      <h2>User info</h2> 
      <!-- あとで編集いるかも -->
     <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "m_e_others_471.jpg" ,format: 'm_e_others_471.jpg' %>

    <table>
    <tbody>
      <tr></tr>
      <tr> 
      <th><h5>name</h5></th>

      <th><%= @user.name %></th>
      </tr>

      
      <tr>
      <th><h5>introduction</h5></th>
      <th></th>
      <th><%= @user.introduction %></th>
      </tr>

    </tbody>
    </table>
     

      <%= link_to"",edit_user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>


       <%= form_for(@book,  url: books_path) do |f| %>

       <h2>New book</h2>
       <h5>title</h5>
        <%= f.text_field :title,class: "col-xs-12" %>

       <h5>opinion</h5>
       <%= f.text_field :body,class: "col-xs-12" %>

       <nev>
         <%= f.submit 'Create Book',class: "col-xs-12 btn btn-primary" %>
       </nev>

      <% end %>
    </div>

    <div class= "col-xs-9">
      <h2>Users</h2>
      <table class='table table-hover table-inverse'>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>


        <% @users.each do |user| %>

        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 20, 20, fallback: "l_e_others_470.jpg",size:'20x20',format: 'l_e_others_470.jpg' %></td>          
          </td>
          <td><%= user.name %><td>
          <td><p>フォロー数 : <%= link_to user.followings.count, followings_path(user) %></p></td>
          <td><p>フォロワー数 : <%= link_to user.followers.count, followers_path(user) %></p></td>
          <td><%= render "relationships/follow_button", user: user %></td>
          <td><%= link_to"Show",user_path(user.id) %></td>
        </tr>
        <% end %>
      </table>
    </div>


  </div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class= "col-xs-3">
      <h2>User info</h2> 
      <!-- あとで編集いるかも -->
     <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "m_e_others_471.jpg" ,format: 'm_e_others_471.jpg' %>

    <table>
    <tbody>
      <tr></tr>
      <tr> 
      <th><h5>name</h5></th>

      <th><%= @user.name %></th>
      </tr>

      
      <tr>
      <th><h5>introduction</h5></th>
      <th></th>
      <th><%= @user.introduction %></th>
      </tr>

      
    </tbody>
    </table>



      <%= link_to"",edit_user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>

      <%= render "relationships/follow_button", user: @user %>

       <%= form_for(@book,  url: books_path) do |f| %>

       <h2>New book</h2>
       <h5>title</h5>
        <%= f.text_field :title,class: "col-xs-12" %>

       <h5>opinion</h5>
       <%= f.text_field :body,class: "col-xs-12" %>

       <nev>
         <%= f.submit 'Create Book',class: "col-xs-12 btn btn-primary" %>
       </nev>
      <% end %>
    </div>

    <div class= "col-xs-9">
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>
        <tr>
          <th></th>
          <th>Title</th>
          <th>opinion</th>
          <th colspan="3"></th>
        </tr>


        <% @books.each do |book| %>
        <%= link_to user_path(@user.id) do %>

        <tr>
          <td><%= attachment_image_tag book.user, :profile_image, :fill, 20, 20, fallback: "l_e_others_470.jpg",size:'20x20',format: 'l_e_others_470.jpg' %>            
          </td>
          <% end %>
          <td><%=link_to book.title, book_path(book.id)%></td>
          <td><%= book.body %></td>

          <!-- いいね -->
          <td><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></td>
        </tr>
        <% end %>
      </table>
    </div>


  </div>
</div>